domain_path: C:\Users\igor4\trash\Documents\DigitalDesign\DF3\vitis\zync_dsp_04\export\zync_dsp_04\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
